package com.demo;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.annotation.Bean;
import org.springframework.context.event.EventListener;

import com.google.common.base.Predicates;

import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;


/**
 * The Class DemoTwitterApplication.
 */
@SpringBootApplication
@EnableSwagger2
public class DemoTwitterApplication {
	
	/** The service. */
	@Autowired
	private TwitterStreamService service;
	
	/**
	 * The main method.
	 *
	 * @param args the arguments
	 */
	public static void main(String[] args)  {
		SpringApplication.run(DemoTwitterApplication.class, args);
	}
	
	/**
	 * Run Twitter Stream service after startup.
	 */
	@EventListener(ApplicationReadyEvent.class)
	public void runTwitterStreamService() {
	    if (service != null) {
	    	service.run();
	    }
	}	
	
//	@Bean
//    public Docket api() {
//		return new Docket(DocumentationType.SWAGGER_2)
//				.select()
//				.apis(RequestHandlerSelectors.basePackage("com.demo"))
//				.paths(PathSelectors.any())
//				.build();
//
//	}

	/**
 * Api.
 *
 * @return the docket
 */
@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).apiInfo(apiInfo()).pathMapping("/").select() // select those paths and api will generate document
				.apis(RequestHandlerSelectors.any()) // Monitor all APIs
				// don't display wrong interface address
				.paths(Predicates.not(PathSelectors.regex("/error.*")))// Error path is not monitored
				.paths(PathSelectors.regex("/.*"))// Monitor all paths under the root
				.build();
	}


	/**
	 * Api info.
	 *
	 * @return the api info
	 */
	private ApiInfo apiInfo() {
		return new ApiInfoBuilder().title("Test twitter Interface Document")
				// .contact(new Contact("rongrong", "", "2250454190@qq.com"))
				// .description("This is the interface document generated by SWAGGER_2")
				// .termsOfServiceUrl("NO terms of service")
				// .license("The Apache License, Version 2.0")
				// .licenseUrl("http://www.apache.org/licenses/LICENSE-2.0.html")
				// .version("v1.0")
				.build();
	}

}
